name: Build iOS IPA
on: [push, workflow_dispatch]

jobs:
  build-ipa:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Cordova
      run: |
        npm install -g cordova
        cordova create build com.technicalgame.shield ShieldApp
        cp index.html build/www/
        cp -r assets/ build/www/ || true
        cd build
        cordova platform add ios
        cordova build ios --device
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: shield-ipa
        path: build/platforms/ios/build/device/*.ipa
