name: Build iOS IPA
on: [push]

jobs:
  build-ipa:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build IPA
      run: |
        sudo npm install -g cordova
        cordova create myapp com.test.app TestApp
        cp index.html myapp/www/
        cd myapp
        cordova platform add ios
        cordova build ios
    - uses: actions/upload-artifact@v4
      with:
        name: ipa-file
        path: myapp/platforms/ios/build/device/*.ipa
